project:
  type: website
  output-dir: ../docs 
  render:
    - "*.qmd"
    - "!outline.qmd"

website:
  title: "Social Networks"

format:
  html:
    link-external-newwindow: true
    theme: cosmo
    css: syllabus.css
    toc: true

editor: source

